### ISSUE TITLE
i could not able to login.. and for your information all the services are running successfully

### ISSUE THREAD

**Issue by balakrishna501** [nikolaslacerda/delivery-microservices-2#1]
![image](https://user-images.githubusercontent.com/29543118/163713758-08161504-e048-4cb8-8f8d-a6d9b8c167d1.png)

**Comment by balakrishna501** [comment]
plz help me on this error

**Comment by balakrishna501** [comment]
it seems customer service is missing

**Comment by nikolaslacerda** [comment]
Hey! Sorry I took so long to reply.
The endpoints were not mapped properly. I fixed it on the last commits.
